### ISSUE TITLE
Keep stopwatch ticking when client closed

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-stopwatch#6]
Currently the `ticking` is done in a process initiated by the browser/client:
https://github.com/dwyl/phoenix-liveview-stopwatch/blob/2617427068ee5727780c2e05d809edd2f63ec3ad/lib/stopwatch_web/live/stopwatch_live.ex#L36-L46

If the status of the timer is `:running` the function will call itself again using the `Process.send_after` function.
However if the client is closed (for example the brwoser tab is closed) then the process die which could leave the Timer agent in an impossible state (`:running` but the `ticking` has stopped)

A solution is to this is to move the `ticking` logic to the Timer agent

**Comment by nelsonic** [comment]
If it's straightforward to fix, go for it. But if not, maybe just add a "known limitation" section to the end of the `README.md` as we would not do this "no database" approach in our _real_ app. 💭

**Comment by SimonLab** [comment]
I was hoping to use `:timer.sleep` in the `tick` function in the Agent.
However this seems to completely froze the timer.

I think `GenServer` should resolved this issue as I would be able to use `Process.send_after` to send the `tick` message to the genserver directly.
see: https://elixirforum.com/t/send-later-to-agent/39027/3

It shouldn't take me to write the Timer version using GenServer and it will be a good occasion to write in the Readme the difference of using Agent vs GenServer

**Comment by nelsonic** [comment]
Appears to be working as expected: https://liveview-stopwatch.fly.dev
![image](https://user-images.githubusercontent.com/194400/175012850-32e3a7a4-b8e6-473e-b996-9376aae5ec8d.png)

Happy to close. ✅
